### ISSUE TITLE
What is the meaning of the Hungarian algorithm to describe the DOA error?

### ISSUE THREAD

**Issue by Qinstudy** [sharathadavanne/seld-dcase2019#10]
In the DCASE 2019 Challenge, you described the Hungarian algorithm to portray the DOA error. I looked up a lot of information, but still didn't understand your explanation. Your formula:
The Hungarian algorithm solves this by estimating the pair-wise costs between individual predicted and reference DOA using the central angle between them：
σ = arccos(sinφE sinφR + cosφE cosφR cos(λR - λE))
What is the meaning of σ, σ is the distance between the reference angle and the predicted angle?
Is there any wonder about your explanation? I am willing to discuss with you.

**Comment by polarch** [comment]
Hi Qinstudy,

σ is exactly the arc distance between two points on the sphere, but measured in radians. You can check this entry:
https://en.wikipedia.org/wiki/Great-circle_distance

In case of DoA data it expresses the angular error. The Hungarian algorithm comes into play when computing a total error for multiple estimates, since each estimate need to be assigned to a ground truth DOA. One intuitive way is to try to find which estimate is closer to which ground truth. If you see the distances from each estimate to each ground truth as costs, the Hungarian algorithm minimizes this total cost, and hence solves the assignment between DOA predictions and ground truths.
