### ISSUE TITLE
Data normalization 

### ISSUE THREAD

**Issue by thomeou** [sharathadavanne/seld-dcase2019#2]
Hi Shara, 

Thank for uploading the codes. I read your feature extraction code in cls_feature_class.py. It seems to me that you compute the scaler (mean, std) using all 4 splits of data. Then you would normalize all of the data using this scaler. However, I think for machine learning, it is not appropriate to normalize unseen data in validation and test split with this scaler. The scaler should be calculated using only training data. Please ignore if this is not the case. 

Best regards,

**Comment by sharathadavanne** [comment]
Thanks for checking the code @thomeou Yes you are right, the correct way of normalizing is to compute the scaler on training split and use it on the testing split. In my experiments with this dataset, the split-wise vs overall normalization provided similar results (Maybe because the dataset is synthesized). Hence I released the implementation which was performing overall normalization, to keep it simple.

**Comment by thomeou** [comment]
Thanks for the clarification!
